# fly.toml app configuration file generated for dcat-oca-api on 2026-02-09T00:05:18-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dcat-oca-api'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  concurrency_limit = 200

[deploy]
  strategy = "immediate"

[checks]
  [checks.health]
    port = 8000
    type = 'http'
    interval = '30s'
    timeout = '10s'
    grace_period = '60s'
    path = '/health'

[[vm]]
  memory = '512mb'
  cpus = 1
